### ISSUE TITLE
Parse failure for link text broken over line

### ISSUE THREAD

**Issue by jgm** [treeman/tree-sitter-djot#11]
E.g.
```
[Word
docx](https://en.wikipedia.org/wiki/Office_Open_XML)
```

**Comment by jgm** [comment]
Same for emphasis
```
*this is
strong*

_this is
emph_
```

And verbatim:
```
`verb
atim`
```

**Comment by treeman** [comment]
Thank you.

A bit confusing about the verbatim, because in the [syntax description](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#verbatim) it says verbatim is closed at newline, but in the live playground it does parse as verbatim as you point out.

**Comment by jgm** [comment]
It doesn't say that verbatim is closed at newline. It says

> If the text to be parsed as inline ends before a closing backtick string is encountered, the verbatim text extends to the end.

But "the text ends" here means that EOF is encountered (not EOL).

**Comment by treeman** [comment]
> But "the text ends" here means that EOF is encountered (not EOL).

I think the key is "as inline", so "end of paragraph" should close the varbatim as well.

I'll need to think of how to do this though.

**Comment by jgm** [comment]
> I think the key is "as inline", so "end of paragraph" should close the varbatim as well.

Yes, that's correct, what I said wasn't right.  But the main point is that newlines inside paragraphs don't end verbatim.
