### ISSUE TITLE
Performance/latency

### ISSUE THREAD

**Issue by jgm** [treeman/tree-sitter-djot#25]
Working with a big file (produced by converting pandoc's MANUAL.txt to djot), I notice significant latency with my djot major mode using this grammar.  There's a noticeable lag between hitting a key in a code block, for example, and seeing it appear on the screen.  There's also a noticeable lag after opening the file.  The problem is serious enough that I wouldn't want to use this major mode.

Earlier things seemed much snappier.  It may be that my impressions were mistaken, but I'm wondering if perhaps some of the changes in the last week or so may have led to performance regressions?

**Comment by treeman** [comment]
Oh dear, that's no good. Being fast enough is a hard requirement.

Yes, there's a very big risk that my changes to try to fix the various emphasis edge cases introduced a performance regressions here https://github.com/treeman/tree-sitter-djot/pull/15 and  https://github.com/treeman/tree-sitter-djot/pull/13. I think they're triggering a lot of LR conflicts that might cause the slowness.

To confirm, could you try to checkout an earlier version of the grammar? 0715e22 for instance should be better?

Is this the file you're testing with? https://github.com/jgm/djoths/blob/main/benchmark/m.dj

**Comment by jgm** [comment]
Yes, that's the file.  Just trying with `tree-sitter parse` I get 190ms with 0715e22, and 296ms with current HEAD.  I haven't figured out how to make Emacs install a specific commit (can do a branch, though), so I haven't tested in that environment.

**Comment by treeman** [comment]
Okay, I've rewritten how newline is handled for inlines here: https://github.com/treeman/tree-sitter-djot/pull/27

This should fix the performance regression I introduced earlier, while still being able to parse as before. There was also some things the parser failed to parse in the large file that I fixed earlier, which should also give a small speed bump.

Please try it out and let me know how it goes.

**Comment by jgm** [comment]
Down to ~ 120ms with `tree-sitter parse.` Nice! I will try in Emacs next.

**Comment by jgm** [comment]
It's pretty snappy in Emacs too. I think you can close this!

**Comment by jgm** [comment]
Further observations in Emacs: I tried with m5.dj (5 copies concatenated), and it started getting sluggish, but still barely tolerable. With m20.dj (20 copies concatenated, 154,000 lines) it was unusably sluggish.  This suggests it's doing a parse of the entire document on each keystroke?  (I don't know how tree-sitter works.)  Anyway, in practice this is  probably not a big deal, unless you are editing whole books in single djot files.

**Comment by treeman** [comment]
Awesome!

Yeah, I think treesitter parses the entire file... I guess if we'd like it to behave differently in order to handle enormous files the editor implementation would need to be updated? In any case it's out of my knowledge zone.

Closing this one.
