### ISSUE TITLE
Handle carriage returns properly

### ISSUE THREAD

**Issue by treeman** [treeman/tree-sitter-djot#31]
Seems broken on Windows, carriage returns are probably the culprit.

**Comment by StratusFearMe21** [comment]
Reproduction steps: In your editor, change the line feed from `LF` to `CRLF`. This will break highlighting

**Comment by treeman** [comment]
I hope I found all the edge cases. If you find any I missed (by comparing `LF` to `CRLF`) please file a ticket and I'll make sure to fix it.
