### ISSUE TITLE
Issue parsing standalone comments

### ISSUE THREAD

**Issue by nature-0** [treeman/tree-sitter-djot#33]
Apparently tree-sitter misses the second type of comment mentionned [here](https://htmlpreview.github.io/?https://github.com/jgm/djot/blob/master/doc/syntax.html#comment).

From what I could guess, **it seems to me that the issue is due to the space before the inline attribute**. 

---

This is not parsed properly:
``` djot
Foo bar {% This is a comment, spanning
multiple lines %} baz.
```

result:
``` scheme
(paragraph {)
```

---

The following is parsed correctly:
``` djot
Foo bar{% This is a comment, spanning
multiple lines %} baz.
```

result:
``` scheme
(paragraph
  (inline_attribute {
   (args
    (comment % (content) %))
   }))
```

**Comment by treeman** [comment]
Nice find, thank you!
